services:
    expansion.bundle.acme.plugins.totot:
        class: eXpansion\Bundle\Acme\Plugins\TotoPlugin
        arguments:
            - '@expansion.service.console'
            - '@expansion.bundle.acme.plugins.gui.windowFactory'
            - '@expansion.helper.usergroups'

    expansion.bundle.acme.plugins.test:
        class: eXpansion\Bundle\Acme\Plugins\Test
        arguments:
            - '@expansion.service.dedicated_connection'
            - '@expansion.service.console'
            - '@expansion.helper.time'
        tags:
            - {name: expansion.plugin, data_provider: mp.legacy.map}
            - {name: expansion.plugin, data_provider: exp.timer}

    expansion.bundle.acme.plugins.gui.windowFactory:
            class: 'eXpansion\Bundle\Acme\Plugins\Gui\WindowFactory'
            arguments:
                index_0: "test window"
                index_1: 180
                index_2: 90
            parent : expansion.framework.core.plugins.gui.window_factory
            tags:
                - {name: expansion.plugin, data_provider: expansion.user_group}
