services:
    expansion.bundle.acme.plugins.totot:
        class: eXpansion\Bundle\Acme\Plugins\TotoPlugin
        arguments:
            - '@expansion.framework.core.services.console'
            - '@expansion.bundle.acme.plugins.gui.windowFactory'
            - '@expansion.framework.core.user_groups.players'
        tags:
            - {name: expansion.plugin, data_provider: expansion.chat_data}

    expansion.bundle.acme.plugins.test:
        class: eXpansion\Bundle\Acme\Plugins\Test
        arguments:
            - '@expansion.framework.core.services.dedicated_connection'
            - '@expansion.framework.core.services.console'
            - '@expansion.framework.core.helpers.time'
        tags:
            - {name: expansion.plugin, data_provider: expansion.match_data}
            - {name: expansion.plugin, data_provider: expansion.timer_data}

    expansion.bundle.acme.plugins.gui.windowFactory:
            class: 'eXpansion\Bundle\Acme\Plugins\Gui\WindowFactory'
            arguments:
                index_0: "test window"
                index_1: 180
                index_2: 90
            parent : expansion.framework.core.plugins.gui.window_factory
            tags:
                - {name: expansion.plugin, data_provider: expansion.user_group}
