eXpansion\Bundle\LocalRecords\Entity\Record:
    type: entity
    table: record
    repositoryClass: eXpansion\Bundle\LocalRecords\Repository\RecordRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mapUid:
            type: string
            length: 255
            column: map_uid
        nbLaps:
            type: integer
            column: nb_laps
            options:
              unsigned: true
        score:
            type: integer
            options:
              unsigned: true
        nbFinish:
            type: integer
            column: nb_finish
            options:
              unsigned: true
        avgScore:
            type: integer
            column: avg_score
            options:
              unsigned: true
        checkpoints:
          type: text
          nullable: true
        date:
          type: datetime

    manyToOne:
        player:
            targetEntity: eXpansion\Framework\PlayersBundle\Entity\Player
            joinColumn:
                name: player_id
                referencedColumnName: id

    uniqueConstraints:
        unicity:
            columns: [map_uid, player_id, nb_laps]
    indexes:
        score_index:
            columns: [score]
    lifecycleCallbacks: {  }
