services:
  maniascript.library.prgfx.text_ext:
    class: eXpansion\Framework\Core\Model\Gui\ManiaScriptFactory
    autowire: true
    arguments:
      $relativePath: 'eXpansionGuiBundle/Resources/maniascript/TextExt.Script.txt'
      $className: eXpansion\Framework\Core\Model\Gui\ManiaScript

  maniascript.library.prgfx.time_ext:
      class: eXpansion\Framework\Core\Model\Gui\ManiaScriptFactory
      autowire: true
      arguments:
        $relativePath: 'eXpansionGuiBundle/Resources/maniascript/Time.Script.txt'
        $className: eXpansion\Framework\Core\Model\Gui\ManiaScript
