services:
    _defaults:
        autowire: true

    expansion.bundle.maps.plugins.chat_commands:
        class: eXpansion\Framework\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@eXpansion\Bundle\Maps\ChatCommand\MapsList'
              - '@eXpansion\Bundle\Maps\ChatCommand\Jukebox'
              - '@eXpansion\Bundle\Maps\ChatCommand\Add'
              - '@eXpansion\Bundle\Maps\ChatCommand\Remove'
              - '@eXpansion\Bundle\Maps\ChatCommand\MxSearch'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.chat_command_data'}

    eXpansion\Bundle\Maps\ChatCommand\:
        resource: '../../ChatCommand'

    eXpansion\Bundle\Maps\ChatCommand\MapsList:
        class: eXpansion\Bundle\Maps\ChatCommand\MapsList
        arguments:
            $command: 'maps'
            $aliases: ['list']

    eXpansion\Bundle\Maps\ChatCommand\Jukebox:
        class: eXpansion\Bundle\Maps\ChatCommand\Jukebox
        arguments:
            $command: 'jukebox'
            $aliases: ['jb']

    eXpansion\Bundle\Maps\ChatCommand\Add:
        class: eXpansion\Bundle\Maps\ChatCommand\Add
        arguments:
            $command:    'addmx'
            $permission: 'jukebox'
            $aliases:    ['add']

    eXpansion\Bundle\Maps\ChatCommand\Remove:
        class: eXpansion\Bundle\Maps\ChatCommand\Remove
        arguments:
            $command:    'removemap'
            $permission: 'jukebox'
            $aliases:    ['remove']

    eXpansion\Bundle\Maps\ChatCommand\MxSearch:
        class: eXpansion\Bundle\Maps\ChatCommand\MxSearch
        arguments:
            $command:    'search'
            $permission: 'jukebox'
            $aliases:    ['mxsearch']
