services:
    expansion.bundle.maps.plugins.chat_commands:
        class: eXpansion\Framework\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@expansion.bundle.maps.chat_commands.mapslist'
              - '@expansion.bundle.maps.chat_commands.jukebox'
              - '@expansion.bundle.maps.chat_commands.add'
              - '@expansion.bundle.maps.chat_commands.remove'
              - '@expansion.bundle.maps.chat_commands.mxsearch'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.chat_command_data'}

    expansion.bundle.maps.chat_commands.mapslist:
        class: eXpansion\Bundle\Maps\ChatCommand\MapsList
        arguments:
            - 'maps'
            - ['list']
            - '@expansion.bundle.maps.gui.window.mapslist_factory'
            - '@expansion.bundle.maps.plugins.maps'

    expansion.bundle.maps.chat_commands.jukebox:
        class: eXpansion\Bundle\Maps\ChatCommand\Jukebox
        arguments:
            - 'jukebox'
            - ['jb']
            - '@expansion.bundle.maps.plugins.jukebox'

    expansion.bundle.maps.chat_commands.add:
        class: eXpansion\Bundle\Maps\ChatCommand\Add
        arguments:
            - 'addmx'
            - 'jukebox'
            - ['add']
            - '@expansion.helper.admingroups'
            - '@expansion.bundle.maps.plugins.maniaexchange'

    expansion.bundle.maps.chat_commands.remove:
        class: eXpansion\Bundle\Maps\ChatCommand\Remove
        arguments:
            - 'removemap'
            - 'jukebox'
            - ['remove']
            - '@expansion.helper.admingroups'
            - '@expansion.bundle.maps.plugins.maps'

    expansion.bundle.maps.chat_commands.mxsearch:
        class: eXpansion\Bundle\Maps\ChatCommand\MxSearch
        arguments:
            - 'search'
            - 'jukebox'
            - ['mxsearch']
            - '@expansion.helper.admingroups'
            - '@expansion.bundle.maps.gui.window.mania_exchange_window_factory'
