services:
    eXpansion.maps.gui.window.mapslist_factory:
        class: 'eXpansion\Bundle\Maps\Plugins\Gui\MapsWindowFactory'
        arguments:
            - 'expansion_maps.gui.window.title'
            - 160
            - 90
            - null
            - null
            - '@expansion.gui.context.window'
            - '@expansion.framework.core.model.gui.grid.builder_factory'
            - '@expansion.framework.core.model.gui.grid.data_collection_factory.array'
            - '@expansion.helper.time'
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}
