services:
    expansion.bundle.maps.plugins.maps:
        class: eXpansion\Bundle\Maps\Plugins\Maps
        arguments:
          - '@expansion.service.dedicated_connection'
          - '@expansion.service.console'
          - '@expansion.helper.admingroups'
          - '@expansion.framework.core.storage.map'
          - '@expansion.helper.chat_notification'
        tags:
          - {name: expansion.plugin, data_provider: mp.legacy.maplist}
          - {name: expansion.plugin, data_provider: mp.legacy.map}
