services:
    _defaults:
        autowire: true
        public: true

    eXpansion\Bundle\Maps\Plugins\Maps:
        class: eXpansion\Bundle\Maps\Plugins\Maps
        tags:
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.maplist'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}

    eXpansion\Bundle\Maps\Plugins\Jukebox:
        class: eXpansion\Bundle\Maps\Plugins\Jukebox
        tags:
          - {name: 'expansion.plugin', data_provider: 'mp.script.podium'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}

    eXpansion\Bundle\Maps\Plugins\ManiaExchange:
        class: eXpansion\Bundle\Maps\Plugins\ManiaExchange
        tags:
          - {name: 'expansion.plugin', data_provider: 'exp.application'}

    eXpansion\Bundle\Maps\Plugins\MenuItems:
        class: eXpansion\Bundle\Maps\Plugins\MenuItems
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.menu.items'}
