services:
    eXpansion\Bundle\Chat\Plugins\Chat:
        class: eXpansion\Bundle\Chat\Plugins\Chat
        autowire: true
        arguments:
            $players: '@expansion.framework.core.user_groups.all_players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.application'}
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.player'}

    eXpansion\Bundle\Chat\Plugins\Gui\Widget\ChatWidgetFactory:
        class:    eXpansion\Bundle\Chat\Plugins\Gui\Widget\ChatWidgetFactory
        autowire: true
        arguments:
            $name:  "Chat"
            $posX: -156
            $posY: -46
            $sizeX: null
            $sizeY: null

    eXpansion\Bundle\Chat\Plugins\Gui\Widget\UpdateChatWidgetFactory:
        class: eXpansion\Bundle\Chat\Plugins\Gui\Widget\UpdateChatWidgetFactory
        autowire: true
        arguments:
            $name:  "UpdateChat"
            $posX: 0
            $posY: 0
            $sizeX: null
            $sizeY: null
