services:
    eXpansion.local_records.gui.window.race_factory:
        class: 'eXpansion\Bundle\LocalRecords\Plugins\Gui\RecordsWindowFactory'
        arguments:
            - 'expansion_local_records.gui.race.window.title'
            - 160
            - 90
            - null
            - null
            - '@expansion.gui.context.window'
            - '@expansion.framework.core.model.gui.grid.builder_factory'
            - '@expansion.framework.core.model.gui.grid.data_collection_factory.array'
            - '@expansion.helper.time'
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}
