services:
    expansion.framework.admin_groups.helpers.groups:
        class: eXpansion\Framework\AdminGroups\Helpers\AdminGroups
        arguments:
            - '@expansion.framework.admin_groups.services.admin_group_configuration'
            - '@expansion.framework.core.user_groups.factory'
