services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\AdminGroups\Plugins\GroupsPlugin:
        class: eXpansion\Framework\AdminGroups\Plugins\GroupsPlugin
        tags:
            - {name: expansion.plugin, data_provider: mp.legacy.player}
