e_xpansion_core:
    parameters:
        core_chat_color_codes:
            error: '$b32'
            warning: '$d50'
            info: '$db1'
            highlight: '$u$fff'

            separator: '$3af'
            pretty_chat: '$dee'

e_xpansion_admin_groups:
    groups:
        master_admin:
            label: Master Admin
            logins:
                - oliverde8
                - reaby
            permissions: [] # Master_admin has always all permissions.
        admin:
            label: Admin
            logins: []
            permissions: [] # To be edited.