e_xpansion_core:
    parameters:
        core_chat_color_codes:
            error: '$b32'
            warning: '$d50'
            info: '$db1'
            highlight: '$u$fff'
            separator: '$3af'
            pretty_chat: '$dee'
            admin_info: '$db1'
            variable: '$fff'
            record: '$3af'
            record_top: '$bdd'
            record_rank: '$dee'
        core_chat_glyph_icons:
            success: '$0d0✔'
            fail: '$b32✘'
            server: '$afd$fff'
            info: ''
            time: ''
e_xpansion_admin_groups:
    groups:
        master_admin:
            label: Master Admin
            logins:
                - oliverde8
                - reaby
            permissions: [] # Master_admin has always all permissions.
        admin:
            label: Admin
            logins: []
            permissions:
              - next
              - restart
