e_xpansion_core:
    parameters:
        core_chat_color_codes:
            error: '$daa'
            warning: '$dda'
            info: '$add'
            primary: '$3af'
            secondary: '$fff'
            highlight: '$fff'
            separator: '$3af'
            pretty_chat: '$dee'
            admin_info: '$db1'
        core_chat_glyph_icons:
            success: '$0d0✔'
            fail: '$b32✘'
            server: '$afd$fff'
            info: ''
            admin: '$daa$fff'
e_xpansion_admin_groups:
    groups:
        master_admin:
            label: Master Admin
            logins:
                - oliverde8
                - reaby
            permissions: [] # Master_admin has always all permissions.
        admin:
            label: Admin
            logins: []
            permissions:
              - next
              - restart
