parameters:
    expansion.core.data_providers.chat_data_provider.class: eXpansion\Core\DataProviders\ChatDataProvider
    expansion.core.data_providers.chat_data_provider.interface: eXpansion\Core\DataProviders\Listener\ChatDataListenerInterface

    expansion.core.data_providers.chat_command_data_provider.class: eXpansion\Core\DataProviders\ChatCommandDataProvider
    expansion.core.data_providers.chat_command_data_provider.interface: eXpansion\Core\DataProviders\Listener\ChatCommandInterface

    expansion.core.data_providers.player_data_provider.class: eXpansion\Core\DataProviders\PlayerDataProvider
    expansion.core.data_providers.player_data_provider.interface: eXpansion\Core\DataProviders\Listener\PlayerDataListenerInterface

    expansion.core.data_providers.map_data_provider.class: eXpansion\Core\DataProviders\MapDataProvider
    expansion.core.data_providers.map_data_provider.interface: eXpansion\Core\DataProviders\Listener\MapDataListenerInterface

    expansion.core.data_providers.match_data_provider.class: eXpansion\Core\DataProviders\MatchDataProvider
    expansion.core.data_providers.match_data_provider.interface: eXpansion\Core\DataProviders\Listener\MatchDataListenerInterface

    expansion.core.data_providers.timer_data_provider.class: eXpansion\Core\DataProviders\TimerDataProvider
    expansion.core.data_providers.timer_data_provider.interface: eXpansion\Core\DataProviders\Listener\TimerDataListenerInterface

    expansion.core.data_providers.user_group_data_provider.class: eXpansion\Core\DataProviders\UserGroupDataProvider
    expansion.core.data_providers.user_group_data_provider.interface: eXpansion\Core\DataProviders\Listener\UserGroupDataListenerInterface


    expansion.core.data_providers.manialink_page_answer_provider.class: eXpansion\Core\DataProviders\ManialinkPageAnswerDataProvider
    expansion.core.data_providers.manialink_page_answer_provider.interface: eXpansion\Core\DataProviders\Listener\ManialinkPageAnswerDataListenerInterface


services:
    expansion.core.data_providers.chat_data_provider:
        class: "%expansion.core.data_providers.chat_data_provider.class%"
        arguments:
            - "@expansion.core.storage.player"
        tags:
            - {name: expansion.data_provider, provider: "expansion.chat_data", interface: "%expansion.core.data_providers.chat_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: PlayerChat, method: onPlayerChat}

    expansion.core.data_providers.chat_command_data_provider:
        class: "%expansion.core.data_providers.chat_command_data_provider.class%"
        arguments:
            - "@expansion.core.services.chat_commands"
        tags:
            - {name: expansion.data_provider, provider: "expansion.chat_command_data", interface: "%expansion.core.data_providers.chat_command_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: PlayerChat, method: onPlayerChat}

    expansion.core.data_providers.player_data_provider:
        class: "%expansion.core.data_providers.player_data_provider.class%"
        arguments:
            - "@expansion.core.storage.player"
            - "@expansion.core.services.dedicated_connection"
            - "@expansion.core.services.application"
        tags:
            - {name: expansion.data_provider, provider: "expansion.player_data", interface: "%expansion.core.data_providers.player_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.run, method: onRun}
            - {name: expansion.data_provider.listener, event_name: PlayerConnect, method: onPlayerConnect}
            - {name: expansion.data_provider.listener, event_name: PlayerDisconnect, method: onPlayerDisconnect}
            - {name: expansion.data_provider.listener, event_name: PlayerInfoChanged, method: onPlayerInfoChanged}
            - {name: expansion.data_provider.listener, event_name: PlayerAlliesChanged, method: onPlayerAlliesChanged}

    expansion.core.data_providers.map_data_provider:
        class: "%expansion.core.data_providers.map_data_provider.class%"
        arguments:
            - "@expansion.core.storage.map"
            - "@expansion.core.services.dedicated_connection"
        tags:
            - {name: expansion.data_provider, provider: "expansion.map_data", interface: "%expansion.core.data_providers.map_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.run, method: onRun}
            - {name: expansion.data_provider.listener, event_name: MapListModified, method: onMapListModified}

    expansion.core.data_providers.match_data_provider:
        class: "%expansion.core.data_providers.match_data_provider.class%"
        arguments:
            - "@expansion.core.storage.player"
            - "@expansion.core.services.dedicated_connection"
        tags:
            - {name: expansion.data_provider, provider: "expansion.match_data", interface: "%expansion.core.data_providers.match_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: BeginMap, method: onBeginMap}
            - {name: expansion.data_provider.listener, event_name: EndMap, method: onEndMap}
            - {name: expansion.data_provider.listener, event_name: BeginMatch, method: onBeginMatch}
            - {name: expansion.data_provider.listener, event_name: EndMatch, method: onEndMatch}
            - {name: expansion.data_provider.listener, event_name: BeginRound, method: onBeginRound}
            - {name: expansion.data_provider.listener, event_name: EndRound, method: onEndRound}
            - {name: expansion.data_provider.listener, event_name: PlayerCheckpoint, method: onPlayerCheckpoint}
            - {name: expansion.data_provider.listener, event_name: PlayerFinish, method: onPlayerFinish}

    expansion.core.data_providers.timer_data_provider:
        class: "%expansion.core.data_providers.timer_data_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.timer_data", interface: "%expansion.core.data_providers.timer_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.pre_loop, method: onPreLoop}
            - {name: expansion.data_provider.listener, event_name: expansion.post_loop, method: onPostLoop}

    expansion.core.data_providers.user_group_provider:
        class: "%expansion.core.data_providers.user_group_data_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.user_group", interface: "%expansion.core.data_providers.user_group_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.user_groups.user_add, method: onExpansionGroupAddUser}
            - {name: expansion.data_provider.listener, event_name: expansion.user_groups.user_remove, method: onExpansionGroupRemoveUser}
            - {name: expansion.data_provider.listener, event_name: expansion.user_groups.group_destroy, method: onExpansionGroupDestroy}

    expansion.core.data_providers.manialink_page_answer_provider:
        class: "%expansion.core.data_providers.manialink_page_answer_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.manialink_page_answer", interface: "%expansion.core.data_providers.manialink_page_answer_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: PlayerManialinkPageAnswer, method: onPlayerManialinkPageAnswer}

