parameters:
    expansion.core.model.hui.manialink.class: 'eXpansion\Core\Model\Gui\Manialink'

services:
    expansion.core.gui.manialink.test:
        class: 'eXpansion\Core\Plugins\Gui\GroupManialinkFactory'
        arguments:
            - "@expansion.core.plugins.gui_handler"
            - "test-manialink"
            - "%expansion.core.model.hui.manialink.class%"
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}
