services:
    expansion.core.helpers.time:
        class: 'eXpansion\Core\Helpers\Time'

    expansion.core.helpers.translations:
        class: 'eXpansion\Core\Helpers\Translations'
        arguments:
            - '@translator'
            - ['fr', 'de', 'fi', 'nl', 'en']

    expansion.core.helpers.chat_notification:
        class: 'eXpansion\Core\Helpers\ChatNotification'
        arguments:
            - '@expansion.core.services.dedicated_connection'
            - '@expansion.core.helpers.translations'
            - '@expansion.core.storage.player'
