services:
    expansion.core.plugins.totot:
        class: eXpansion\Core\Plugins\TotoPlugin
        arguments:
            - '@expansion.core.services.console'
            - '@expansion.core.gui.manialink.test'
            - '@expansion.core.user_groups.players'
        tags:
            - {name: expansion.plugin, data_provider: expansion.chat_data}