services:
    expansion.core.plugins.totot:
        class: eXpansion\Core\Plugins\TotoPlugin
        tags:
            - {name: expansion.plugin, data_provider: expansion.chat_data}
        arguments:
            - '@expansion.core.services.console'
