services:
    expansion.core.plugins.totot:
        class: eXpansion\Core\Plugins\TotoPlugin
        arguments:
            - '@expansion.core.services.console'
        tags:
            - {name: expansion.plugin, data_provider: expansion.chat_data}

    expansion.core.plugins.joinleave:
        class: eXpansion\Core\Plugins\JoinLeaveMessages
        arguments:
            - '@expansion.core.services.dedicated_connection'
            - '@expansion.core.services.console'
        tags:
            - {name: expansion.plugin, data_provider: expansion.player_data}

