parameters:
    expansion.core.services.dedicated_connection.class: Maniaplanet\DedicatedServer\Connection
    expansion.core.services.dedicated_connection.factory.class: eXpansion\Core\Services\DedicatedConnection\Factory

    expansion.core.services.application.class: eXpansion\Core\Services\Application
    expansion.core.services.plugin_manager.class: eXpansion\Core\Services\PluginManager
    expansion.core.services.data_provider_manager.class: eXpansion\Core\Services\DataProviderManager
    expansion.core.services.console.class: eXpansion\Core\Services\Console

services:
    expansion.core.services.dedicated_connection.factory:
        class: "%expansion.core.services.dedicated_connection.factory.class%"
        arguments:
            - "%dedicated_host%"
            - "%dedicated_port%"
            - "%dedicated_timeout%"
            - "%dedicated_user%"
            - "%dedicated_password%"

    expansion.core.services.dedicated_connection:
        class: "%expansion.core.services.dedicated_connection.class%"
        factory: "expansion.core.services.dedicated_connection.factory:createConnection"

    expansion.core.services.gui_handler:
        class: 'eXpansion\Core\Services\GuiHandler'
        arguments:
            - "@expansion.core.services.dedicated_connection"

    expansion.core.services.application:
        class: "%expansion.core.services.application.class%"
        arguments:
            - '@expansion.core.services.application.dispatcher'
            - '@expansion.core.services.dedicated_connection'
            - '@expansion.core.services.gui_handler'
            - '@expansion.core.services.console'

    expansion.core.services.application_debug:
        class: eXpansion\Core\Services\ApplicationDebug
        arguments:
            - '@expansion.core.services.application.dispatch_logger'
            - '@expansion.core.services.dedicated_connection'
            - '@expansion.core.services.console'

    expansion.core.services.application.dispatcher:
        class: eXpansion\Core\Services\Application\Dispatcher
        arguments:
            - '@expansion.core.services.data_provider_manager'
            - '@expansion.core.services.plugin_manager'

    expansion.core.services.application.dispatch_logger:
        class: eXpansion\Core\Services\Application\DispatchLogger
        arguments:
            - '@expansion.core.services.console'

    expansion.core.services.plugin_manager:
        class: "%expansion.core.services.plugin_manager.class%"
        arguments:
            - '@service_container'
            - '@expansion.core.services.model.plugin.plugin_description_factory'
            - '@expansion.core.services.data_provider_manager'

    expansion.core.services.data_provider_manager:
        class: "%expansion.core.services.data_provider_manager.class%"
        arguments:
            - '@service_container'

    expansion.core.services.console:
        class: "%expansion.core.services.console.class%"
        arguments:
            - '%color_enabled%'

    expansion.core.services.model.plugin.plugin_description_factory:
        class: 'eXpansion\Core\Model\Plugin\PluginDescriptionFactory'
        arguments:
            - 'eXpansion\Core\Model\Plugin\PluginDescription'
