services:
    eXpansion\Bundle\Admin\Plugins\MenuItems:
        class: eXpansion\Bundle\Admin\Plugins\MenuItems
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.menu.items'}
