services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eXpansion\Framework\Core\Command\:
        resource: '../../Command/*'

    eXpansion\Framework\Core\Command\GenRecordsCommand:
        class: eXpansion\Framework\Core\Command\GenRecordsCommand

