parameters:
    expansion.framework.core.data_providers.chat_data_provider.class: eXpansion\Framework\Core\DataProviders\ChatDataProvider
    expansion.framework.core.data_providers.chat_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\ChatDataListenerInterface

    expansion.framework.core.data_providers.chat_command_data_provider.class: eXpansion\Framework\Core\DataProviders\ChatCommandDataProvider
    expansion.framework.core.data_providers.chat_command_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\ChatCommandInterface

    expansion.framework.core.data_providers.player_data_provider.class: eXpansion\Framework\Core\DataProviders\PlayerDataProvider
    expansion.framework.core.data_providers.player_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\PlayerDataListenerInterface

    expansion.framework.core.data_providers.map_data_provider.class: eXpansion\Framework\Core\DataProviders\MapDataProvider
    expansion.framework.core.data_providers.map_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\MapDataListenerInterface

    expansion.framework.core.data_providers.match_data_provider.class: eXpansion\Framework\Core\DataProviders\MatchDataProvider
    expansion.framework.core.data_providers.match_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\MatchDataListenerInterface

    expansion.framework.core.data_providers.timer_data_provider.class: eXpansion\Framework\Core\DataProviders\TimerDataProvider
    expansion.framework.core.data_providers.timer_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\TimerDataListenerInterface

    expansion.framework.core.data_providers.user_group_data_provider.class: eXpansion\Framework\Core\DataProviders\UserGroupDataProvider
    expansion.framework.core.data_providers.user_group_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\UserGroupDataListenerInterface

    expansion.framework.core.data_providers.manialink_page_answer_provider.class: eXpansion\Framework\Core\DataProviders\ManialinkPageAnswerDataProvider
    expansion.framework.core.data_providers.manialink_page_answer_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\ManialinkPageAnswerDataListenerInterface

    expansion.framework.core.data_providers.script_data_provider.class: eXpansion\Framework\Core\DataProviders\ScriptDataProvider
    expansion.framework.core.data_providers.script_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\ScriptDataListenerInterface

    expansion.framework.core.data_providers.application_data_provider.class: eXpansion\Framework\Core\DataProviders\ApplicationDataProvider
    expansion.framework.core.data_providers.application_data_provider.interface: eXpansion\Framework\Core\DataProviders\Listener\ApplicationDataListenerInterface

services:
    expansion.framework.core.data_providers.chat_data_provider:
        class: "%expansion.framework.core.data_providers.chat_data_provider.class%"
        arguments:
            - "@expansion.framework.core.storage.player"
        tags:
            - {name: expansion.data_provider, provider: "expansion.chat_data", interface: "%expansion.framework.core.data_providers.chat_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: PlayerChat, method: onPlayerChat}

    expansion.framework.core.data_providers.chat_command_data_provider:
        class: "%expansion.framework.core.data_providers.chat_command_data_provider.class%"
        arguments:
            - "@expansion.framework.core.services.chat_commands"
            - "@expansion.framework.core.helpers.chat_notification"
            - "@expansion.framework.core.helpers.chat_output"
        tags:
            - {name: expansion.data_provider, provider: "expansion.chat_command_data", interface: "%expansion.framework.core.data_providers.chat_command_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: PlayerChat, method: onPlayerChat}

    expansion.framework.core.data_providers.player_data_provider:
        class: "%expansion.framework.core.data_providers.player_data_provider.class%"
        arguments:
            - "@expansion.framework.core.storage.player"
            - "@expansion.framework.core.services.dedicated_connection"
            - "@expansion.framework.core.services.application"
        tags:
            - {name: expansion.data_provider, provider: "expansion.player_data", interface: "%expansion.framework.core.data_providers.player_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.run, method: onRun}
            - {name: expansion.data_provider.listener, event_name: PlayerConnect, method: onPlayerConnect}
            - {name: expansion.data_provider.listener, event_name: PlayerDisconnect, method: onPlayerDisconnect}
            - {name: expansion.data_provider.listener, event_name: PlayerInfoChanged, method: onPlayerInfoChanged}
            - {name: expansion.data_provider.listener, event_name: PlayerAlliesChanged, method: onPlayerAlliesChanged}

    expansion.framework.core.data_providers.map_data_provider:
        class: "%expansion.framework.core.data_providers.map_data_provider.class%"
        arguments:
            - "@expansion.framework.core.storage.map"
            - "@expansion.framework.core.services.dedicated_connection"
        tags:
            - {name: expansion.data_provider, provider: "expansion.map_data", interface: "%expansion.framework.core.data_providers.map_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: MapListModified, method: onMapListModified}

    expansion.framework.core.data_providers.match_data_provider:
        class: "%expansion.framework.core.data_providers.match_data_provider.class%"
        arguments:
            - "@expansion.framework.core.storage.player"
            - "@expansion.framework.core.services.dedicated_connection"
        tags:
            - {name: expansion.data_provider, provider: "expansion.match_data", interface: "%expansion.framework.core.data_providers.match_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: BeginMap, method: onBeginMap}
            - {name: expansion.data_provider.listener, event_name: EndMap, method: onEndMap}

    expansion.framework.core.data_providers.timer_data_provider:
        class: "%expansion.framework.core.data_providers.timer_data_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.timer_data", interface: "%expansion.framework.core.data_providers.timer_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.pre_loop, method: onPreLoop}
            - {name: expansion.data_provider.listener, event_name: expansion.post_loop, method: onPostLoop}

    expansion.framework.core.data_providers.user_group_provider:
        class: "%expansion.framework.core.data_providers.user_group_data_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.user_group", interface: "%expansion.framework.core.data_providers.user_group_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.user_groups.user_add, method: onExpansionGroupAddUser}
            - {name: expansion.data_provider.listener, event_name: expansion.user_groups.user_remove, method: onExpansionGroupRemoveUser}
            - {name: expansion.data_provider.listener, event_name: expansion.user_groups.group_destroy, method: onExpansionGroupDestroy}

    expansion.framework.core.data_providers.manialink_page_answer_provider:
        class: "%expansion.framework.core.data_providers.manialink_page_answer_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.manialink_page_answer", interface: "%expansion.framework.core.data_providers.manialink_page_answer_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: PlayerManialinkPageAnswer, method: onPlayerManialinkPageAnswer}


    expansion.framework.core.data_providers.script_data_provider:
        class: "%expansion.framework.core.data_providers.script_data_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.script", interface: "%expansion.framework.core.data_providers.script_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL, gamemode: script}
            - {name: expansion.data_provider.listener, event_name: ModeScriptCallbackArray, method: onModeScriptCallbackArray}

    expansion.framework.core.data_providers.application_data_provider:
        class: "%expansion.framework.core.data_providers.application_data_provider.class%"
        tags:
            - {name: expansion.data_provider, provider: "expansion.application", interface: "%expansion.framework.core.data_providers.application_data_provider.interface%"}
            - {name: expansion.data_provider.compatibility, title: ALL}
            - {name: expansion.data_provider.listener, event_name: expansion.init, method: onApplicationInit}
            - {name: expansion.data_provider.listener, event_name: expansion.ready, method: onApplicationReady}
            - {name: expansion.data_provider.listener, event_name: expansion.stop, method: onApplicationStop}
