parameters:
    expansion.framework.core.model.gui.manialink.class: 'eXpansion\Framework\Core\Model\Gui\Manialink'
    expansion.framework.core.model.gui.window.class: 'eXpansion\Framework\Core\Model\Gui\Window'
    expansion.framework.core.model.gui.widget.class: 'eXpansion\Framework\Core\Model\Gui\Widget'
    expansion.framework.core.model.gui.action.class: 'eXpansion\Framework\Core\Model\Gui\Action'

services:

    #
    # GUI Contexes to put everything together.
    #
    expansion.gui.context.manialink:
        class: 'eXpansion\Framework\Core\Model\Gui\ManialinkFactoryContext'
        arguments:
            - "%expansion.framework.core.model.gui.manialink.class%"
            - "@expansion.framework.core.plugins.gui_handler"
            - "@expansion.framework.core.user_groups.factory"
            - "@expansion.framework.core.plugins.gui.action_factory"

    expansion.gui.context.widget:
        class: 'eXpansion\Framework\Core\Model\Gui\WidgetFactoryContext'
        arguments:
            - "%expansion.framework.core.model.gui.widget.class%"
            - "@expansion.framework.core.plugins.gui_handler"
            - "@expansion.framework.core.user_groups.factory"
            - "@expansion.framework.core.plugins.gui.action_factory"
            - "@expansion.helper.translations"
            - "@expansion.gui.component.factory"


    expansion.gui.context.window:
        class: 'eXpansion\Framework\Core\Model\Gui\WindowFactoryContext'
        arguments:
            - "%expansion.framework.core.model.gui.window.class%"
            - "@expansion.framework.core.plugins.gui_handler"
            - "@expansion.framework.core.user_groups.factory"
            - "@expansion.framework.core.plugins.gui.action_factory"
            - "@expansion.helper.translations"
            - "@expansion.gui.component.factory"
            - "@expansion.framework.core.mania_script.window_factory"

    #
    # GUI Element factories
    #
    expansion.framework.core.gui.element.factory.label:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\LabelFactory'

    expansion.framework.core.gui.element.factory.back_ground:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\BackGroundFactory'

    expansion.framework.core.gui.element.factory.title_back_ground:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\TitleBackGroundFactory'

    expansion.framework.core.gui.element.factory.line:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\LineFactory'
        arguments:
            - '@expansion.framework.core.gui.element.factory.back_ground'
            - '@expansion.framework.core.gui.element.factory.label'

    expansion.framework.core.gui.element.factory.title_line:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\LineFactory'
        arguments:
            - '@expansion.framework.core.gui.element.factory.title_back_ground'
            - '@expansion.framework.core.gui.element.factory.label'
            - 'title'

    expansion.framework.core.gui.element.factory.pager:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\PagerFactory'
        arguments:
            - '@expansion.framework.core.gui.element.factory.label'

    #
    # Default window factories.
    #
    expansion.framework.core.plugins.gui.window_help_factory:
        class: 'eXpansion\Framework\Core\Plugins\Gui\WindowHelpFactory'
        arguments:
            - 'expansion_core.windows.chat_commands.title'
            - 180
            - 90
            - null
            - null
            - '@expansion.gui.context.window'
            - '@expansion.gui.gridbuilder.factory'
            - '@expansion.gui.gridbuilder.datacollection.array'
            - '@expansion.service.chat_commands'
            - '@expansion.framework.core.data_providers.chat_command_data_provider'
            - '@expansion.framework.core.plugins.gui.window_help_description_factory'
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}

    expansion.framework.core.plugins.gui.window_help_description_factory:
        class: 'eXpansion\Framework\Core\Plugins\Gui\WindowHelpDetailsFactory'
        arguments:
            - 'expansion_core.windows.chat_commands_description.title'
            - 180
            - 90
            - null
            - null
            - '@expansion.gui.context.window'
            - '@expansion.framework.core.gui.element.factory.line'
            - '@expansion.framework.core.gui.element.factory.title_line'
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}
