parameters:
    expansion.framework.core.model.gui.grid.data_collection.class: 'eXpansion\Framework\Core\Model\Gui\Grid\DataCollection'
    expansion.framework.core.model.gui.grid.data_collection_factory.class: 'eXpansion\Framework\Core\Model\Gui\Grid\DataCollectionFactory'

    expansion.framework.core.model.gui.grid.grid_builder.class: 'eXpansion\Framework\Core\Model\Gui\Grid\GridBuilder'

services:
    expansion.gui.gridbuilder.datacollection.array:
        class: '%expansion.framework.core.model.gui.grid.data_collection_factory.class%'
        arguments:
            - "@expansion.helper.data.array_filter"
            - "%expansion.framework.core.model.gui.grid.data_collection.class%"

    expansion.gui.gridbuilder.datacollection.object:
        class: '%expansion.framework.core.model.gui.grid.data_collection_factory.class%'
        arguments:
            - "@expansion.helper.data.object_filter"
            - "%expansion.framework.core.model.gui.grid.data_collection.class%"

    expansion.gui.gridbuilder.factory:
        class: 'eXpansion\Framework\Core\Model\Gui\Grid\GridBuilderFactory'
        arguments:
            - '%expansion.framework.core.model.gui.grid.grid_builder.class%'
            - '@expansion.framework.core.plugins.gui.action_factory'
            - '@expansion.framework.core.gui.element.factory.line'
            - '@expansion.framework.core.gui.element.factory.title_line'
            - '@expansion.framework.core.gui.element.factory.pager'
