parameters:
    expansion.framework.core.model.gui.grid.data_collection.class: 'eXpansion\Framework\Core\Model\Gui\Grid\DataCollection'
    expansion.framework.core.model.gui.grid.data_collection_factory.class: 'eXpansion\Framework\Core\Model\Gui\Grid\DataCollectionFactory'

services:
    expansion.framework.core.model.gui.grid.data_collection_factory.array:
        class: '%expansion.framework.core.model.gui.grid.data_collection_factory.class%'
        arguments:
            - "@expansion.framework.core.helpers.data.array_filter"
            - "%expansion.framework.core.model.gui.grid.data_collection.class%"

    expansion.framework.core.model.gui.grid.data_collection_factory.object:
        class: '%expansion.framework.core.model.gui.grid.data_collection_factory.class%'
        arguments:
            - "@expansion.framework.core.helpers.data.object_filter"
            - "%expansion.framework.core.model.gui.grid.data_collection.class%"
