services:
    expansion.framework.core.helpers.time:
        class: 'eXpansion\Framework\Core\Helpers\Time'

    expansion.framework.core.helpers.translations:
        class: 'eXpansion\Framework\Core\Helpers\Translations'
        arguments:
            - '@translator'
            - ['fr', 'de', 'fi', 'nl', 'en']
            - '%expansion.config.core_chat_color_codes%'
            - '%expansion.config.core_chat_glyph_icons%'

    expansion.framework.core.helpers.chat_notification:
        class: 'eXpansion\Framework\Core\Helpers\ChatNotification'
        arguments:
            - '@expansion.framework.core.services.dedicated_connection'
            - '@expansion.framework.core.helpers.translations'
            - '@expansion.framework.core.storage.player'

    expansion.framework.core.helpers.chat_output:
        class: 'eXpansion\Framework\Core\Helpers\ChatOutput'
        arguments:
            - '@expansion.framework.core.services.dedicated_connection'
            - '@expansion.framework.core.helpers.chat_notification'

    expansion.framework.core.helpers.data.array_filter:
        class: 'eXpansion\Framework\Core\Helpers\Data\ArrayFilter'

    expansion.framework.core.helpers.data.object_filter:
        class: 'eXpansion\Framework\Core\Helpers\Data\ObjectFilter'