services:
    expansion.helper.time:
        class: eXpansion\Framework\Core\Helpers\Time

    expansion.helper.translations:
        class: eXpansion\Framework\Core\Helpers\Translations
        arguments:
            - '@translator'
            - ['fr', 'de', 'fi', 'nl', 'en']
            - '%expansion.config.core_chat_color_codes%'
            - '%expansion.config.core_chat_glyph_icons%'

    expansion.helper.chat_notification:
        class: eXpansion\Framework\Core\Helpers\ChatNotification
        arguments:
            - '@expansion.service.dedicated_connection'
            - '@expansion.helper.translations'
            - '@expansion.storage.player'
            - '@expansion.service.console'

    expansion.helper.chat_output:
        class: eXpansion\Framework\Core\Helpers\ChatOutput
        arguments:
            - '@expansion.service.dedicated_connection'
            - '@expansion.helper.chat_notification'

    expansion.helper.http:
        class: eXpansion\Framework\Core\Helpers\Http
        arguments: ['@expansion.service.jobrunner.factory']


    expansion.helper.data.array_filter:
        class: 'eXpansion\Framework\Core\Helpers\Data\ArrayFilter'

    expansion.helper.data.object_filter:
        class: 'eXpansion\Framework\Core\Helpers\Data\ObjectFilter'
