parameters:

services:
    expansion.framework.core.listener.base_storage_update:
        class: 'eXpansion\Framework\Core\Listener\BaseStorageUpdateListener'
        arguments:
            - '@expansion.framework.core.services.dedicated_connection'
            - "@expansion.framework.core.storage.game_data"
            - '@expansion.framework.core.services.application.dispatcher'
        tags:
            - { name: kernel.event_listener, event: maniaplanet.game.BeginMap }
