services:
  expansion.framework.core.maniascript.window:
    class: eXpansion\Framework\Core\Model\Gui\ManiaScriptFactory
    autowire: true
    arguments:
      $relativePath: 'eXpansion/Core/Resources/maniascript/window.txtm'
      $className: eXpansion\Framework\Core\Model\Gui\ManiaScript

