parameters:
  expansion.framework.core.model.gui.mania_script.class: 'eXpansion\Framework\Core\Model\Gui\ManiaScript'
  expansion.framework.core.model.gui.mania_scrip_factoryt.class: 'eXpansion\Framework\Core\Model\Gui\ManiaScriptFactory'

  expansion.framework.core.mania_script.window.path: 'eXpansionCore/Resources/mania_script/window.txtm'

services:
  expansion.framework.core.mania_script.window_factory:
    class: '%expansion.framework.core.model.gui.mania_scrip_factoryt.class%'
    arguments:
      - '%expansion.framework.core.mania_script.window.path%'
      - '@file_locator'
      - '%expansion.framework.core.model.gui.mania_script.class%'