parameters:
    expansion.service.dedicated_connection.class: Maniaplanet\DedicatedServer\Connection
    expansion.service.dedicated_connection.factory.class: eXpansion\Framework\Core\Services\DedicatedConnection\Factory
    expansion.service.application.class: eXpansion\Framework\Core\Services\Application
    expansion.service.plugin_manager.class: eXpansion\Framework\Core\Services\PluginManager
    expansion.service.data_provider_manager.class: eXpansion\Framework\Core\Services\DataProviderManager
    expansion.service.console.class: eXpansion\Framework\Core\Services\Console
    expansion.service.chat_commands.class: eXpansion\Framework\Core\Services\ChatCommands
    expansion.service.chat_commands.depth: 3

services:
    expansion.service.dedicated_connection.factory:
        class: "%expansion.service.dedicated_connection.factory.class%"
        arguments:
            - "%dedicated_host%"
            - "%dedicated_port%"
            - "%dedicated_timeout%"
            - "%dedicated_user%"
            - "%dedicated_password%"

    expansion.service.dedicated_connection:
        class: "%expansion.service.dedicated_connection.class%"
        factory: "expansion.service.dedicated_connection.factory:createConnection"

    expansion.service.application:
        class: "%expansion.service.application.class%"
        arguments:
            - '@expansion.service.dispatcher'
            - '@expansion.service.dedicated_connection'
            - '@expansion.service.console'

    expansion.service.application_debug:
        class: eXpansion\Framework\Core\Services\ApplicationDebug
        arguments:
            - '@expansion.service.application.dispatch_logger'
            - '@expansion.service.dedicated_connection'
            - '@expansion.service.console'

    expansion.service.dispatcher:
        class: eXpansion\Framework\Core\Services\Application\Dispatcher
        arguments:
            - '@expansion.service.data_provider_manager'
            - '@expansion.service.plugin_manager'
        calls:
            - [addEventProcesseor, ['@expansion.service.symfony_event_adapter']]

    expansion.service.symfony_event_adapter:
        class: eXpansion\Framework\Core\Services\SymfonyEventAdapter
        arguments:
            - '@event_dispatcher'

    expansion.service.application.dispatch_logger:
        class: eXpansion\Framework\Core\Services\Application\DispatchLogger
        arguments:
            - '@expansion.service.console'

    expansion.service.plugin_manager:
        class: "%expansion.service.plugin_manager.class%"
        arguments:
            - '@service_container'
            - '@expansion.service.model.plugin.plugin_description_factory'
            - '@expansion.service.data_provider_manager'
            - '@expansion.storage.gamedata'
            - '@expansion.service.console'

    expansion.service.data_provider_manager:
        class: "%expansion.service.data_provider_manager.class%"
        arguments:
            - '@service_container'
            - '@expansion.storage.gamedata'
            - '@expansion.service.console'

    expansion.service.console:
        class: "%expansion.service.console.class%"
        arguments:
            - '%color_enabled%'

    expansion.service.chat_commands:
        class: "%expansion.service.chat_commands.class%"
        arguments:
          - '%expansion.service.chat_commands.depth%'

    expansion.service.model.plugin.plugin_description_factory:
        class: 'eXpansion\Framework\Core\Model\Plugin\PluginDescriptionFactory'
        arguments:
            - 'eXpansion\Framework\Core\Model\Plugin\PluginDescription'

    expansion.service.jobrunner.factory:
        class: eXpansion\Framework\Core\Helpers\JobRunner\Factory
        tags:
            - {name: expansion.plugin, data_provider: exp.timer}
