parameters:
    expansion.framework.core.storage.player.class: eXpansion\Framework\Core\Storage\PlayerStorage
    expansion.framework.core.storage.map.class: eXpansion\Framework\Core\Storage\MapStorage
    expansion.framework.core.storage.game_data.class: eXpansion\Framework\Core\Storage\GameDataStorage

    expansion.framework.core.storage.game_data.mode.codes:
        0 : script
        1 : round
        2 : timeattack
        3 : team
        4 : laps
        5 : cup
        6 : stunts

    expansion.framework.core.storage.data.player.class: eXpansion\Framework\Core\Storage\Data\Player
    expansion.framework.core.storage.data.player.factory: eXpansion\Framework\Core\Storage\Data\PlayerFactory

services:
    expansion.framework.core.storage.player:
        class: "%expansion.framework.core.storage.player.class%"
        arguments:
            - "@expansion.framework.core.services.dedicated_connection"
            - "@expansion.framework.core.storage.data.player.factory"

    expansion.framework.core.storage.map:
        class: "%expansion.framework.core.storage.map.class%"
        arguments:
            - "@expansion.framework.core.services.dedicated_connection"

    expansion.framework.core.storage.game_data:
        class: "%expansion.framework.core.storage.game_data.class%"
        arguments:
          - "%expansion.framework.core.storage.game_data.mode.codes%"

    expansion.framework.core.storage.data.player.factory:
        class: "%expansion.framework.core.storage.data.player.factory%"
        arguments:
            - "%expansion.framework.core.storage.data.player.class%"