parameters:
    expansion.storage.player.class: eXpansion\Framework\Core\Storage\PlayerStorage
    expansion.storage.map.class: eXpansion\Framework\Core\Storage\MapStorage
    expansion.framework.core.storage.game_data.class: eXpansion\Framework\Core\Storage\GameDataStorage

    expansion.framework.core.storage.game_data.mode.codes:
        0 : script
        1 : round
        2 : timeattack
        3 : team
        4 : laps
        5 : cup
        6 : stunts

    expansion.framework.core.storage.game_data.titles:
        'TMStadium@nadeo': 'TM'
        'TMStadium':       'TM'
        'TMValley@nadeo':  'TM'
        'TMValley':        'TM'
        'TMCanyon@nadeo':  'TM'
        'TMCanyon':        'TM'
        'TMLagoon@nadeo':  'TM'
        'TMLagoon':        'TM'


    expansion.framework.core.storage.data.player.class: eXpansion\Framework\Core\Storage\Data\Player
    expansion.framework.core.storage.data.player.factory: eXpansion\Framework\Core\Storage\Data\PlayerFactory

services:
    expansion.storage.player:
        class: "%expansion.storage.player.class%"
        arguments:
            - "@expansion.service.dedicated_connection"
            - "@expansion.framework.core.storage.data.player.factory"

    expansion.storage.map:
        class: "%expansion.storage.map.class%"
        arguments:
            - "@expansion.service.dedicated_connection"

    expansion.framework.core.storage.game_data:
        class: "%expansion.framework.core.storage.game_data.class%"
        arguments:
          - "%expansion.framework.core.storage.game_data.mode.codes%"
          - "%expansion.framework.core.storage.game_data.titles%"

    expansion.framework.core.storage.data.player.factory:
        class: "%expansion.framework.core.storage.data.player.factory%"
        arguments:
            - "%expansion.framework.core.storage.data.player.class%"
