parameters:
    expansion.framework.core.model.user_groups.group.class: eXpansion\Framework\Core\Model\UserGroups\Group

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    expansion.framework.core.user_groups.all_players:
        class: '%expansion.framework.core.model.user_groups.group.class%'
        arguments:
            $name: 'all_players'

    expansion.framework.core.user_groups.players:
        class: '%expansion.framework.core.model.user_groups.group.class%'
        arguments:
            $name: 'players'

    expansion.framework.core.user_groups.spectators:
        class: '%expansion.framework.core.model.user_groups.group.class%'
        arguments:
            $name: 'spectators'

    eXpansion\Framework\Core\Plugins\UserGroups\Factory:
        class: eXpansion\Framework\Core\Plugins\UserGroups\Factory
        arguments:
            $class: '%expansion.framework.core.model.user_groups.group.class%'
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}
            - {name: expansion.plugin, data_provider: mp.legacy.player}
