services:
    expansion.admin_chat.chat_command.base:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AbstractConnectionCommand
        arguments:
            - '__'
            - '__'
            - []
            - '@expansion.framework.admin_groups.helpers.groups'
            - '@expansion.framework.core.services.dedicated_connection'
            - '@expansion.framework.core.helpers.chat_notification'
            - '@expansion.framework.core.storage.player'
            - '@logger'
            - '@expansion.framework.core.helpers.time'

    expansion.admin_chat.chat_command.restart:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "restart"
            index_1: "restart"
            index_2: ['res', 'restartmap']
        calls:
            - [setDescription, ["expansion_admin_chat.restart.description"]]
            - [setChatMessage, ["expansion_admin_chat.restart.msg"]]
            - [setFunctionName, ["restartMap"]]

    expansion.admin_chat.chat_command.next:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "next"
            index_1: "next"
            index_2: ['skip', 'nextmap']
        calls:
            - [setDescription, ["expansion_admin_chat.next.description"]]
            - [setChatMessage, ["expansion_admin_chat.next.msg"]]
            - [setFunctionName, ["nextMap"]]

    expansion.admin_chat.chat_command.set_server_name:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "setservername"
            index_1: "set_server_name"
            index_2: ['name']
        calls:
            - [setParameterDescription, ['sets new server name, uses "" if spaces used.']]
            - [setDescription, ["expansion_admin_chat.set_server_name.description"]]
            - [setChatMessage, ["expansion_admin_chat.set_server_name.msg"]]
            - [setFunctionName, ["setServerName"]]

    expansion.admin_chat.chat_command.set_server_name:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "setservercomment"
            index_1: "set_server_name"
            index_2: ['comment']
        calls:
            - [setParameterDescription, ['sets new server comment, use "" if spaces used.']]
            - [setDescription, ["expansion_admin_chat.set_server_comment.description"]]
            - [setChatMessage, ["expansion_admin_chat.set_server_comment.msg"]]
            - [setFunctionName, ["setServerComment"]]

    expansion.admin_chat.chat_command.kick:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "kick"
            index_1: "kick"
            index_2: []
        calls:
            - [setParameterLoginDescription, ["Login of player to kick."]]
            - [setParameterReasonDescription, ["The reason for kicking."]]
            - [setDescription, ["expansion_admin_chat.kick.description"]]
            - [setChatMessage, ["expansion_admin_chat.kick.msg"]]
            - [setFunctionName, ["kick"]]

    expansion.admin_chat.chat_command.ban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "ban"
            index_1: "ban"
            index_2: []
        calls:
            - [setParameterLoginDescription, ["Login of player to ban."]]
            - [setParameterReasonDescription, ["The reason for banning."]]
            - [setDescription, ["expansion_admin_chat.ban.description"]]
            - [setChatMessage, ["expansion_admin_chat.ban.msg"]]
            - [setFunctionName, ["ban"]]


    expansion.admin_chat.chat_command.unban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "unban"
            index_1: "unban"
            index_2: []
        calls:
            - [setParameterDescription, ['unban player by login']]
            - [setDescription, ["expansion_admin_chat.unban.description"]]
            - [setChatMessage, ["expansion_admin_chat.unban.msg"]]
            - [setFunctionName, ["unBan"]]

    expansion.admin_chat.chat_command.black:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "black"
            index_1: "black"
            index_2: []
        calls:
            - [setParameterLoginDescription, ["Login of player to black."]]
            - [setParameterReasonDescription, ["The reason for black listing."]]
            - [setDescription, ["expansion_admin_chat.black.description"]]
            - [setChatMessage, ["expansion_admin_chat.black.msg"]]
            - [setFunctionName, ["banAndBlackList"]]

    expansion.admin_chat.chat_command.unblack:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "unblack"
            index_1: "unblack"
            index_2: []
        calls:
            - [setParameterDescription, ['Unblack Player by login']]
            - [setDescription, ["expansion_admin_chat.unblack.description"]]
            - [setChatMessage, ["expansion_admin_chat.unblack.msg"]]
            - [setFunctionName, ["unBlacklist"]]

    expansion.admin_chat.chat_command.planets:
          class: eXpansion\Bundle\AdminChat\ChatCommand\AdminReturnCommand
          parent: expansion.admin_chat.chat_command.base
          arguments:
              index_0: "planets"
              index_1: "planets"
              index_2: []
          calls:
              - [setDescription, ["expansion_admin_chat.planets.description"]]
              - [setChatMessage, ["expansion_admin_chat.planets.msg"]]
              - [setFunctionName, ["getServerPlanets"]]
              - [setPublic, [false]]

    expansion.admin_chat.chat_command.ignore:
          class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
          parent: expansion.admin_chat.chat_command.base
          arguments:
              index_0: "ignore"
              index_1: "ignore"
              index_2: []
          calls:
              - [setParameterDescription, ['Ignores player by login']]
              - [setDescription, ["expansion_admin_chat.ignore.description"]]
              - [setChatMessage, ["expansion_admin_chat.ignore.msg"]]
              - [setFunctionName, ["ignore"]]

    expansion.admin_chat.chat_command.unignore:
          class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
          parent: expansion.admin_chat.chat_command.base
          arguments:
              index_0: "unignore"
              index_1: "unignore"
              index_2: []
          calls:
              - [setParameterDescription, ['Unignores player by login']]
              - [setDescription, ["expansion_admin_chat.unignore.description"]]
              - [setChatMessage, ["expansion_admin_chat.unignore.msg"]]
              - [setFunctionName, ["unignore"]]
