services:
    expansion.admin_chat.chat_command.base:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AbstractConnectionCommand
        arguments:
            - '__'
            - '__'
            - []
            - '@expansion.framework.admin_groups.helpers.groups'
            - '@expansion.framework.core.services.dedicated_connection'
            - '@expansion.framework.core.helpers.chat_notification'
            - '@expansion.framework.core.storage.player'
            - '@logger'

    expansion.admin_chat.chat_command.restart:
        class: eXpansion\Bundle\AdminChat\ChatCommand\Restart
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "restart"
            index_1: "restart"
            index_2: ['res', 'restartmap']

    expansion.admin_chat.chat_command.next:
        class: eXpansion\Bundle\AdminChat\ChatCommand\Next
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "next"
            index_1: "next"
            index_2: ['skip', 'nextmap']


    expansion.admin_chat.chat_command.set_server_name:
        class: eXpansion\Bundle\AdminChat\ChatCommand\SetServerName
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "setservername"
            index_1: "set_server_name"
            index_2: []

    expansion.admin_chat.chat_command.kick:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "kick"
            index_1: "kick"
            index_2: []
            index_8: "Login of player to kick."
            index_9: "The reason for kicking."
            index_10: "expansion_admin_chat.kick.description"
            index_11: "expansion_admin_chat.kick.msg"
            index_12: "kick"

    expansion.admin_chat.chat_command.ban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "ban"
            index_1: "ban"
            index_2: []
            index_8: "Login of player to ban."
            index_9: "The reason for banning."
            index_10: "expansion_admin_chat.ban.description"
            index_11: "expansion_admin_chat.ban.msg"
            index_12: "ban"


    expansion.admin_chat.chat_command.unban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\Unban
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "unban"
            index_1: "unban"
            index_2: []


    expansion.admin_chat.chat_command.black:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "black"
            index_1: "black"
            index_2: []
            index_8: "Login of player to black."
            index_9: "The reason for black listing."
            index_10: "expansion_admin_chat.black.description"
            index_11: "expansion_admin_chat.black.msg"
            index_12: "banAndBlackList"

    expansion.admin_chat.chat_command.unblack:
        class: eXpansion\Bundle\AdminChat\ChatCommand\Unblack
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "unblack"
            index_1: "unblack"
            index_2: []
