services:
    expansion.admin_chat.chat_command.base:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AbstractConnectionCommand
        arguments:
            - '__'
            - '__'
            - []
            - '1'
            - '@expansion.admin_groups.helpers.groups'
            - '@expansion.framework.core.services.dedicated_connection'
            - '@expansion.framework.core.helpers.chat_notification'
            - '@expansion.framework.core.storage.player'

    expansion.admin_chat.chat_command.restart:
        class: eXpansion\Bundle\AdminChat\ChatCommand\Restart
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "restart"
            index_1: "restart"
            index_2: ['res', 'restartmap']

    expansion.admin_chat.chat_command.next:
        class: eXpansion\Bundle\AdminChat\ChatCommand\Next
        parent: expansion.admin_chat.chat_command.base
        arguments:
            index_0: "next"
            index_1: "next"
            index_2: ['skip', 'nextmap']
