parameters:

services:
    # Plugin that register chat commands that work with all gamemodes & titles.
    expansion.admin_chat.plugins.generic_chat_commands:
        class: eXpansion\Framework\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@expansion.admin_chat.chat_command.restart'
              - '@expansion.admin_chat.chat_command.next'
              - '@expansion.admin_chat.chat_command.set_server_name'
              - '@expansion.admin_chat.chat_command.kick'
              - '@expansion.admin_chat.chat_command.ban'
              - '@expansion.admin_chat.chat_command.unban'
              - '@expansion.admin_chat.chat_command.black'
              - '@expansion.admin_chat.chat_command.unblack'

        tags:
            - {name: expansion.plugin, data_provider: expansion.chat_command_data}
