services:
    _defaults:
        autowire: true
        autoconfigure: true

    eXpansion\Framework\PlayersBundle\Repository\PlayerRepository:
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - eXpansion\Framework\PlayersBundle\Entity\Player