services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eXpansion\Framework\GameManiaplanet\ScriptMethods\GetScores:
        class: eXpansion\Framework\GameManiaplanet\ScriptMethods\GetScores
        tags:
            - {name: expansion.plugin, data_provider: mp.method.get_scores}