sercices:
    eXpansion\Bundle\ImmersiveWindows\Plugins\WindowsGuiHandler:
        class: eXpansion\Bundle\ImmersiveWindows\Plugins\WindowsGuiHandler
        autowire: true
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.player'}

    eXpansion\Bundle\ImmersiveWindows\Model\Gui\Factory\WindowFrameFactory:
        class: eXpansion\Bundle\ImmersiveWindows\Model\Gui\Factory\WindowFrameFactory
        autowire: true

    # Replace native one with ours.
    eXpansion\Framework\Core\Model\Gui\Factory\WindowFrameFactory: '@eXpansion\Bundle\ImmersiveWindows\Model\Gui\Factory\WindowFrameFactory'