services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    expansion.bundle.votemanager.plugins.chat_commands:
        class: eXpansion\Framework\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@eXpansion\Bundle\VoteManager\ChatCommand\Skip'
              - '@eXpansion\Bundle\VoteManager\ChatCommand\Restart'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.chat_command_data'}

    eXpansion\Bundle\VoteManager\ChatCommand\:
        resource: '../../ChatCommand'

    eXpansion\Bundle\VoteManager\ChatCommand\Restart:
        class: eXpansion\Bundle\VoteManager\ChatCommand\Restart
        arguments:
            $command: 'replay'
            $aliases: ['res', 'restart']

    eXpansion\Bundle\VoteManager\ChatCommand\Skip:
        class: eXpansion\Bundle\VoteManager\ChatCommand\Skip
        arguments:
            $command: 'skip'
            $aliases: ['nextmap']
