services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\VoteManager\Plugins\VoteManager:
        class: eXpansion\Bundle\VoteManager\Plugins\VoteManager
        arguments:
            $players: '@expansion.framework.core.user_groups.players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.vote'}
            - {name: 'expansion.plugin', data_provider: 'exp.application'}
            - {name: 'expansion.plugin', data_provider: 'exp.timer'}

    eXpansion\Bundle\VoteManager\Plugins\Gui\Widget\VoteWidgetFactory:
            class: eXpansion\Bundle\VoteManager\Plugins\Gui\Widget\VoteWidgetFactory
            autowire: true
            arguments:
                $name:  "Vote"
                $posX: -120
                $posY: 65
                $sizeX: null
                $sizeY: null

    eXpansion\Bundle\VoteManager\Plugins\Gui\Widget\UpdateVoteWidgetFactory:
            class: eXpansion\Bundle\VoteManager\Plugins\Gui\Widget\UpdateVoteWidgetFactory
            autowire: true
            arguments:
                $name:  "UpdateVote"
                $posX: 0
                $posY: 0
                $sizeX: null
                $sizeY: null
