services:
    eXpansion\Bundle\CustomUi\Plugins\CustomUi:
        class: eXpansion\Bundle\CustomUi\Plugins\CustomUi
        autowire: true
        tags:
          - {name: 'expansion.plugin', data_provider: 'exp.application'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.player'}
