parameters:
    expansion.framework.game_trackmania.data_providers.base.class: eXpansion\Framework\GameTrackmania\DataProviders\BaseDataProvider
    expansion.framework.game_trackmania.data_providers.base.interface: eXpansion\Framework\Core\DataProviders\Listener\ChatDataListenerInterface

services:
    expansion.framework.game_trackmania.data_providers.base:
        class: "%expansion.framework.game_trackmania.data_providers.base.class%"
        arguments:
            - "@expansion.framework.core.storage.player"
        tags:
            - {name: expansion.data_provider, provider: "expansion.tm.base", interface: "%expansion.framework.game_trackmania.data_providers.base.interface%"}
            - {name: expansion.data_provider.compatibility, title: TM, gamemode: script}
            - {name: expansion.data_provider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint}
