parameters:
    expansion.framework.game_trackmania.data_providers.base.class: eXpansion\Framework\GameTrackmania\DataProviders\BaseDataProvider
    expansion.framework.game_trackmania.data_providers.base.interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\BaseDataListenerInterface

services:
    expansion.framework.game_trackmania.data_providers.base:
        class: "%expansion.framework.game_trackmania.data_providers.base.class%"
        arguments:
            - "@expansion.storage.player"
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.race", interface: "%expansion.framework.game_trackmania.data_providers.base.interface%"}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint}
