services:
    expansion.core.plugins.joinleave:
        class: eXpansion\Bundle\JoinLeaveMessages\Plugins\JoinLeaveMessages
        arguments:
            - '@expansion.core.services.dedicated_connection'
            - '@expansion.core.services.console'
        tags:
            - {name: expansion.plugin, data_provider: expansion.player_data}