services:
    eXpansion\Bundle\JoinLeaveMessages\Plugins\JoinLeaveMessages:
        autowire: true
        class: eXpansion\Bundle\JoinLeaveMessages\Plugins\JoinLeaveMessages
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.player'}

