eXpansion\Framework\PlayersBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: eXpansion\Framework\PlayersBundle\Repository\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        login:
            type: string
            length: 255
            unique: true
        nickname:
            type: string
            length: 255
        nicknameStripped:
            type: string
            length: 255
        path:
            type: string
            length: 255
        wins:
            type: integer
            unsigned: true
        onlineTime:
            type: integer
            unsigned: true
        lastOnline:
            type: datetime

    lifecycleCallbacks: {  }
