services:
   expansion.framework.core.plugins.mxkarma.connection:
        class: eXpansion\Bundle\MxKarma\Plugins\Connection
        arguments:
            - '@expansion.service.application.dispatcher'

   expansion.framework.core.plugins.mxkarma:
        class: eXpansion\Bundle\MxKarma\Plugins\MxKarma
        arguments:
            - '@expansion.framework.core.plugins.mxkarma.connection'
            - '@expansion.service.console'
            - '@expansion.helper.chat_notification'
            - '@expansion.service.application.dispatcher'
        tags:
            - {name: expansion.plugin, data_provider: mp.script.match}
            - {name: expansion.plugin, data_provider: mp.legacy.chat}
