services:
    _defaults:
        autowire: true

    eXpansion\Bundle\MxKarma\Plugins\:
        resource: '../../Plugins/*'

    eXpansion\Bundle\MxKarma\Plugins\MxKarma:
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.application'}
            - {name: 'expansion.plugin', data_provider: 'mp.script.map'}
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.chat'}
            - {name: 'expansion.plugin', data_provider: 'exp.plugin.mxkarma'}
