services:

    expansion.framework.core.gui.scripts.menu:
        class: '%expansion.framework.core.model.gui.mania_scrip_factory.class%'
        arguments:
          - 'MenuBundle/Resources/mania_script/menu.txtm'
          - '@file_locator'
          - '%expansion.framework.core.model.gui.mania_script.class%'


    expansion.framework.core.plugins.gui.menu:
        class: eXpansion\Bundle\Menu\Plugins\Gui\MenuFactory
        arguments:
            - 'Menu Factory'
            - 0
            - 0
            - null
            - null
            - '@expansion.gui.context.widget'
            - '@expansion.framework.core.gui.scripts.menu'
            - '@expansion.helper.admingroups'
        tags:
            - {name: expansion.plugin, data_provider: expansion.user_group}
