services:
    eXpansion\Bundle\Menu\Plugins\Menu:
        class: eXpansion\Bundle\Menu\Plugins\Menu
        autowire: true
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}
