services:
    expansion.framework.core.plugins.menu:
        class: eXpansion\Bundle\Menu\Plugins\Menu
        arguments:
            - '@expansion.helper.admingroups'
            - '@expansion.framework.core.plugins.gui.menu'
        tags:
            - {name: expansion.plugin, data_provider: mp.legacy.map}
