services:
    _defaults:
        autowire: true

    expansion.emotes.chat_command.bb:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        arguments:
            $command:    "bb"
            $nbMessages: "5"
            $aliases:    ['bye']

    expansion.emotes.chat_command.gg:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        arguments:
            $command:    "gg"
            $nbMessages: "2"
            $aliases:    ['goodgame']

    expansion.emotes.chat_command.thx:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        arguments:
            $command:    "thx"
            $nbMessages: "3"
            $aliases:    ['thanks']
