services:
    expansion.emotes.chat_command.good_game:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        arguments:
            - "gg"
            - "expansion_emotes.gg"
            - '@expansion.core.helpers.chat_notification'
            - '@expansion.core.storage.player'
            - ['goodgame']