services:
    expansion.emotes.chat_command.base:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        arguments:
            - '__'
            - ['__']
            - '1'
            - '@expansion.framework.core.helpers.chat_notification'
            - '@expansion.framework.core.storage.player'

    expansion.emotes.chat_command.bb:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        parent: expansion.emotes.chat_command.base
        arguments:
            index_0: "bb"
            index_1: "6"
            index_2: ['bye']

    expansion.emotes.chat_command.gg:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        parent: expansion.emotes.chat_command.base
        arguments:
            index_0: "gg"
            index_1: "2"
            index_2: ['goodgame']

    expansion.emotes.chat_command.thx:
        class: eXpansion\Bundle\Emotes\ChatCommand\BasicEmote
        parent: expansion.emotes.chat_command.base
        arguments:
            index_0: "thx"
            index_1: "3"
            index_2: ['thanks']
