parameters:

services:
    expansion.emotes.plugins.chat_commands:
        class: eXpansion\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@expansion.emotes.chat_command.gg'
              - '@expansion.emotes.chat_command.bb'
              - '@expansion.emotes.chat_command.thx'
        tags:
            - {name: expansion.plugin, data_provider: expansion.chat_command_data}