services:
    expansion.bundle.custom_chat.plugins.custom_chat:
        class: eXpansion\Bundle\CustomChat\Plugins\CustomChat
        arguments:
          - '@expansion.service.dedicated_connection'
          - '@expansion.service.console'
          - '@expansion.helper.admingroups'
        tags:
          - {name: expansion.plugin, data_provider: mp.legacy.chat}
          - {name: expansion.plugin, data_provider: exp.application}
