services:
    eXpansion\Bundle\CustomChat\Plugins\CustomChat:
        class: eXpansion\Bundle\CustomChat\Plugins\CustomChat
        autowire: true
        tags:
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.chat'}
          - {name: 'expansion.plugin', data_provider: 'exp.application'}
